"""v0.2 UI tests using actual Quasar. All execution/SCM states are samples.
Directory picker success/cancel/error paths are stubbed; the fallback uses
Playwright's file-input injection. Neither validates an OS-native picker dialog.
"""
import argparse, json, re, shutil, tempfile
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
parser=argparse.ArgumentParser()
parser.add_argument('--html',type=Path,required=True)
parser.add_argument('--output',type=Path,default=Path('test-results/v2'))
a=parser.parse_args();a.output.mkdir(parents=True,exist_ok=True)
html=a.html.read_text(encoding='utf-8');results=[];errors=[];network=[]

def passed(name):
    results.append({'name':name,'passed':True}); print('PASS:',name,flush=True)

with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=shutil.which('chromium') or None,headless=True,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1440,'height':1050},device_scale_factor=1)
    page.set_default_timeout(6000)
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda req:network.append(req.url))
    def reset():
        page.goto('about:blank'); page.set_content(html,wait_until='load')
    def click(name):page.get_by_role('button',name=name,exact=True).click()
    def nav(name):page.locator('.nav-item').filter(has_text=name).click()
    def row(name):return page.locator('.service-row').filter(has=page.locator('.service-title strong',has_text=name))
    def settle():page.wait_for_timeout(2400)
    reset()
    expect(page.locator('.service-row')).to_have_count(7)
    expect(page.locator('.instance-group').filter(has_text='Java · 2 实例')).to_have_count(1)
    expect(page.locator('.project-context')).to_contain_text('6 个运行配置 · 7 个实例')
    passed('Project → 6 configurations → 7 independently identified instances')
    page.locator('.service-search input').fill('Python')
    expect(page.locator('.service-row')).to_have_count(1);page.locator('.service-search input').fill('')
    passed('Instance search preserves group hierarchy')
    row('业务服务 · 02').get_by_role('button',name='运行业务服务 · 02',exact=True).click();settle()
    expect(row('业务服务 · 01').locator('.status')).to_have_text('运行中')
    expect(row('业务服务 · 02').locator('.status')).to_have_text('运行中')
    passed('Two instances of the same Java configuration run together')
    row('业务服务 · 02').get_by_role('button',name='停止业务服务 · 02',exact=True).click()
    expect(row('业务服务 · 01').locator('.status')).to_have_text('运行中')
    expect(row('业务服务 · 02').locator('.status')).to_have_text('已停止')
    passed('Stopping one instance does not stop sibling')
    row('业务服务 · 01').click();click('模拟代码改动');settle()
    expect(page.locator('.info-grid')).to_contain_text('v4')
    click('模拟编译失败');page.wait_for_timeout(1350)
    expect(page.locator('.info-grid')).to_contain_text('v4');expect(page.locator('.issue-row')).to_have_count(1)
    expect(row('业务服务 · 01').locator('.status')).to_have_text('运行中')
    passed('Build failure preserves the running version')
    click('重试更新');settle();expect(page.locator('.issue-row')).to_have_count(0)
    passed('Retry clears the correct instance issue')
    click('复制为新实例')
    expect(page.get_by_role('combobox',name='实例运行配置')).to_have_value('api')
    page.get_by_role('spinbutton',name='实例数量').fill('2')
    page.get_by_role('spinbutton',name='起始端口').fill('8080')
    click('添加 2 个实例');expect(page.locator('.form-error')).to_contain_text('冲突')
    passed('Duplicate instances reject conflicting configured ports')
    page.get_by_role('spinbutton',name='起始端口').fill('8082');click('添加 2 个实例')
    expect(page.locator('.service-row')).to_have_count(9)
    expect(page.locator('.project-context')).to_contain_text('6 个运行配置 · 9 个实例')
    expect(row('业务服务 · 03')).to_contain_text(':8082');expect(row('业务服务 · 04')).to_contain_text(':8083')
    passed('Batch creation reuses one configuration with separate sequential ports')
    click('实例设置')
    page.locator('.config-form').get_by_text('公共启动命令',exact=True).locator('input').fill('java -jar service.jar')
    click('保存配置');row('业务服务 · 01').click();click('实例设置')
    expect(page.locator('.config-form').get_by_text('公共启动命令',exact=True).locator('input')).to_have_value('java -jar service.jar')
    expect(page.locator('.config-form input[type=number]')).to_have_value('8080')
    passed('Shared command changes propagate, but instance port is independent')
    page.get_by_role('combobox',name='选择项目').select_option('sandbox')
    expect(page.locator('.service-row')).to_have_count(0);expect(page.locator('.empty-project-detail')).to_be_visible()
    expect(page.locator('.log-row')).to_have_count(0)
    passed('Empty projects have safe empty states and isolated logs')
    click('清空日志')
    click('添加第一个实例')
    page.locator('.modal label').filter(has_text='语言 / 运行类型').locator('select').select_option('JavaScript')
    page.locator('.modal').get_by_text('实例名称前缀',exact=True).locator('input').fill('独立 Vite')
    click('添加 1 个实例')
    expect(page.locator('.service-row')).to_have_count(1)
    passed('A new Vite configuration belongs to the selected project, not a new project')
    click('运行独立 Vite · 01');settle();click('停止本项目')
    page.get_by_role('combobox',name='选择项目').select_option('commerce')
    expect(row('业务服务 · 01').locator('.status')).to_have_text('运行中')
    passed('Project batch stop does not touch another project')
    click('运行日志'); assert page.locator('.log-row').count()>0
    passed('Clearing another project log does not erase this project log')
    # Actual API is NOT invoked; test success metadata handling with a directory handle stub.
    page.evaluate("window.showDirectoryPicker=async () => ({name:'ChosenFolder',kind:'directory'});")
    nav('项目管理');page.locator('.heading-actions').get_by_role('button',name='创建项目',exact=True).click()
    click('选择文件夹');expect(page.locator('.folder-choice')).to_contain_text('ChosenFolder')
    page.locator('.modal-actions').get_by_role('button',name='创建项目',exact=True).click()
    expect(page.locator('.project-context')).to_contain_text('ChosenFolder')
    expect(page.locator('.service-row')).to_have_count(0)
    passed('Directory API success (stubbed) creates a named project without inventing an absolute path')
    nav('代码管理');expect(page.locator('.vcs-empty')).to_contain_text('还没有已连接')
    passed('Chosen local project is not assigned fake Git diffs')
    nav('项目管理');page.locator('.heading-actions').get_by_role('button',name='创建项目',exact=True).click()
    page.evaluate("() => { window.showDirectoryPicker=async () => {throw new DOMException('cancel','AbortError')}; }")
    click('选择文件夹');expect(page.locator('.folder-choice')).to_contain_text('选择电脑上的文件夹')
    expect(page.locator('.form-error')).to_have_count(0)
    passed('Directory cancellation is harmless and does not create a project')
    page.evaluate("() => { window.showDirectoryPicker=async () => {throw new DOMException('denied','SecurityError')}; }")
    click('选择文件夹');expect(page.locator('.pick-folder')).to_have_text('兼容选择')
    passed('Directory denial offers fallback without claiming access')
    with tempfile.TemporaryDirectory(prefix='noide-picker-') as td:
        directory=Path(td)/'FallbackProject';directory.mkdir();(directory/'README.txt').write_text('not uploaded',encoding='utf-8')
        page.locator('input[webkitdirectory]').set_input_files(str(directory))
        expect(page.locator('.folder-choice')).to_contain_text('FallbackProject')
        expect(page.locator('input[webkitdirectory]')).to_have_value('')
    passed('Fallback directory input records name then releases File references')
    page.locator('.modal-actions').get_by_role('button',name='创建项目',exact=True).click()
    expect(page.locator('.project-context')).to_contain_text('FallbackProject')
    # Repository import is only a pending request.
    page.evaluate("window.showDirectoryPicker=async () => ({name:'Downloads',kind:'directory'});")
    nav('项目管理');page.locator('.heading-actions').get_by_role('button',name='创建项目',exact=True).click()
    click('从仓库获取');click('选择文件夹')
    page.locator('.modal').get_by_text('项目名称',exact=False).filter(has=page.locator('input')).locator('input').fill('ImportedApp')
    page.locator('.modal').get_by_text('仓库地址',exact=True).locator('input').fill('https://example.invalid/team/app.git')
    page.locator('.modal-actions').get_by_role('button',name='创建项目',exact=True).click()
    nav('代码管理');expect(page.locator('.vcs-empty')).to_contain_text('尚未 clone / checkout')
    expect(page.locator('.repo-actions .q-btn').first).to_be_disabled()
    passed('Clone / checkout entry remains explicitly pending with no fabricated fetch or diff')
    # Reset isolates SCM sample tests.
    reset();nav('代码管理')
    expect(page.locator('.changed-file')).to_have_count(3)
    expect(page.locator('.diff-code')).to_contain_text('findPage(page, 20)')
    expect(page.locator('.diff-code')).to_contain_text('findAll()')
    passed('Git diff renders actual differences between bounded sample texts')
    click('统一');expect(page.locator('.diff-code')).to_have_class('diff-code unified')
    click('并排');expect(page.locator('.diff-code')).to_have_class('diff-code split')
    passed('Unified / split diff toggle')
    page.get_by_role('button',name=re.compile('^拉取代码')).click()
    expect(page.locator('.vcs-info')).to_contain_text('已阻止更新');expect(page.locator('.changed-file')).to_have_count(3)
    passed('Dirty pull is blocked conservatively without losing local changes')
    page.get_by_role('checkbox',name='暂存 services/order/OrderController.java').check()
    page.locator('#commit-message').fill('fix: 分页查询')
    page.get_by_role('button',name=re.compile('^提交到本地')).click()
    expect(page.locator('.vcs-confirm')).to_contain_text('1 个文件');click('确认演示')
    expect(page.locator('.changed-file')).to_have_count(2)
    expect(page.locator('.sync-count')).to_contain_text('↑ 1')
    passed('Git commits only staged file, leaves unstaged files and increments unpushed count')
    page.get_by_role('button',name=re.compile('^推送')).click();expect(page.locator('.vcs-confirm')).to_contain_text('origin/main')
    click('取消');expect(page.locator('.sync-count')).to_contain_text('↑ 1')
    page.get_by_role('button',name=re.compile('^推送')).click();click('确认演示')
    expect(page.locator('.sync-count')).to_contain_text('↑ 0')
    passed('Push requires its own confirmation and cancel is non-mutating')
    click('全部暂存 / 取消');page.locator('#commit-message').fill('feat: 本地开发配置')
    page.get_by_role('button',name=re.compile('^提交到本地')).click();click('确认演示')
    page.get_by_role('button',name=re.compile('^拉取代码')).click();click('确认演示')
    expect(page.locator('.vcs-info')).to_contain_text('没有请求真实仓库')
    passed('Clean pull demo explicitly reports no real repository request')
    page.get_by_role('combobox',name='选择代码仓库').select_option('commerce-svn')
    expect(page.get_by_role('combobox',name='差异范围')).to_have_count(0)
    expect(page.locator('.repo-actions')).not_to_contain_text('推送')
    expect(page.locator('.vcs-tabs')).to_contain_text('没有 Git 暂存区')
    passed('SVN update/commit semantics are separate from Git stage/push')
    page.get_by_role('checkbox',name='选择 src/OrderValidator.java').check()
    page.locator('#commit-message').fill('fix: 订单校验')
    page.get_by_role('button',name=re.compile('^提交到 SVN')).click()
    expect(page.locator('.vcs-confirm')).to_contain_text('确认远端提交');click('确认演示')
    expect(page.locator('.changed-file')).to_have_count(1)
    page.get_by_role('button',name=re.compile('^提交记录')).click()
    expect(page.locator('.vcs-history')).to_contain_text('r129')
    expect(page.locator('.vcs-history')).to_contain_text('已到示例远端')
    passed('SVN commits only checked files and advances sample remote revision')
    page.get_by_role('button',name=re.compile('^本地变更')).click();click('模拟冲突')
    expect(page.locator('.conflict-banner')).to_be_visible()
    page.get_by_role('checkbox',name='选择 README.md').check();page.locator('#commit-message').fill('do not commit conflicts')
    expect(page.get_by_role('button',name=re.compile('^提交到 SVN'))).to_be_disabled()
    page.get_by_role('button',name=re.compile('^更新工作副本')).click()
    expect(page.locator('.vcs-info')).to_contain_text('存在未解决冲突')
    passed('Unresolved conflict blocks update and commit')
    click('保留当前内容并标记解决（演示）');expect(page.locator('.conflict-banner')).to_have_count(0)
    passed('Explicit sample conflict resolution does not claim a disk write')
    # Project ownership: model remains intact across navigation.
    page.get_by_role('combobox',name='选择项目').select_option('sandbox');nav('代码管理')
    expect(page.locator('.vcs-empty')).to_be_visible()
    page.get_by_role('combobox',name='选择项目').select_option('commerce');nav('代码管理')
    expect(page.locator('.changed-file')).to_have_count(0)
    passed('Repository change state belongs to the project and survives page switches')
    # Fresh screenshots and responsive checks, both running view and SCM.
    for width,height,label in [(1440,1050,'desktop'),(1024,900,'landscape'),(768,1024,'tablet'),(390,844,'mobile')]:
        page.set_viewport_size({'width':width,'height':height});reset()
        dims=page.evaluate('({view:innerWidth,body:document.documentElement.scrollWidth})')
        assert dims['view']>=dims['body'],dims
        page.screenshot(path=str(a.output/f'{label}-run.png'),full_page=True)
        if label=='mobile':click('展开导航')
        nav('代码管理');page.wait_for_timeout(120)
        dims=page.evaluate('({view:innerWidth,body:document.documentElement.scrollWidth})')
        assert dims['view']>=dims['body'],dims
        page.screenshot(path=str(a.output/f'{label}-vcs.png'),full_page=True)
        passed(f'{width}px run/SCM pages: no document-level horizontal overflow')
    assert not errors,errors;passed('No uncaught JavaScript errors')
    assert not network,network;passed('No requests for selected files, preview responses or SCM actions')
    mode=page.locator('html').get_attribute('data-renderer');assert mode=='quasar'
    browser.close()
report={'renderer':mode,'scope':'Quasar UI/sample states only; directory API stub + fallback input injection, no native OS dialog or backend validation','checks':results,'uncaught_errors':errors,'network_requests':network}
(a.output/'results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(report,ensure_ascii=False,indent=2))
